### ISSUE TITLE
dev dependencies not compatible to flutter 3.3.10 stable

### ISSUE THREAD

**Issue by reke592** [daegalus/dart-uuid#104]
```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (12 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

dart-uuid pubspec.yaml
```
environment:
  sdk: ">=2.14.0 <4.0.0"
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
```

project depends on test >=1.24.4 which requires SDK version >=3.0.0 <4.0.0, version solving failed.
